import random

from common import *
from grasp import msa_grasp

logging.basicConfig(filename='app.log', format='%(asctime)s - %(message)s', level=logging.INFO)

real_seqs = [
    'GCGGGTCACTGAGGGCTGGGATGAGGACGGCCACCACTTCGAGGAGTCCCTTCACTACGAGGGCAGGGCCGTGGACATCACCACGTCAGACAGGGACAAGAGCAAGTACGGCACCCTGTCCAGACTGGCGGTGGAAGCTGGGTTCGACTGGGTCTACTATGAGTCCAAAGCGCACATCCACTGCTCTGTGAAAGCAGAAAGCTCAGTCGCTGCAAAGTCGGGCGGTTGCTTCCCAGGATCCTCCACGGTCACCCTGGAAAATGGCACCCAGAGGCCCGTCAAAGATCTCCAACCCGGGGACAGAGTACTGGCCGCGGATTACGACGGAAACCCGGTTTATACCGACTTCATCATGTTCAA',
    'CTACGGCAGAAGAAGACATCCGAAAAAGCTGACACCTCTCGCCTACAAGCAGTTCATACCTAATGTCGCGGAGAAGACCTTAGGGGCCAGCGGCAGATACGAGGGCAAGATAACGCGCAATTCGGAGAGATTTAAAGAACTTACTCCAAATTACAATCCCGACATTATCTTTAAGGATGAGGAGAACACG',
    'CTACGGCAGAAGAAGACATCCCAAGAAGCTGACACCTCTCGCCTACAAGCAGTTTATACCTAATGTCGCGGAGAAGACCTTAGGGGCCAGCGGCAGATACGAGGGCAAGATCACGCGCAATTCGGAGAGATTTAAAGAACTTACTCCAAATTACAATCCCGACATTATCTTTAAGGATGAGGAGAACACT',
    'TGCTGCTGCTGGCGAGATGTCTGCTGGTGCTGCTTGTCTCCTCGCTGTTGATGTGCTCGGGGCTGGCGTGCGGACCCGGCAGGGGATTTGGCAAGAGGCGGAACCCCAAAAAGCTGACCCCTTTAGCCTACAAGCAGTTTATCCCCAACGTGGCGGAGAAGACCCTAGGGGCCAGTGGAAGATATGAGGGGAAGATCACCAGAAACTCAGAGCGATTTAAGGAACTCACCCCCAATTACAACCC']


def generate_instance(seqs, cnt, lenght):
    res = []
    for n in range(cnt):
        src = seqs[n % len(seqs)]
        min_start = len(src) - lenght - 1
        ini = random.randint(0, min_start)
        fin = ini + lenght
        res.append(src[ini:fin])
    return res


instances = [generate_instance(real_seqs, 4, 60) for _ in range(10)]


def main():
    alpha = 'abcdefghijklmnñopqrstuvwxyz'
    for j, i in enumerate(instances):
        log('=' * 60)
        log('Instance:', alpha[j])
        log('=' * 60)
        for s in i: log(' ', s)
        log('=' * 60)
        sol, score = msa_grasp(i)
        log('=' * 60)
        log('Score:', score)
        for r in sol: log(' ', r)
        log('=' * 60)


if __name__ == '__main__':
    main()
